"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, CalendarClock, Check, Eye, LayoutTemplate, Mail, MessageCircleMore, Save, Send, UsersRound } from "lucide-react";
import { AppPage, Breadcrumbs, Button, EmptyState, InlineError, SectionCard, Select } from "@esse-beauty/ui";
import { MODULE_KEYS, useModuleEnabled } from "@esse-beauty/feature-flags";
import { useAuth } from "../../../../lib/auth-context";
import { EmailPreview, PushPreview, PushTextEditor, RichTextEditor } from "../_components/MarketingEditors";

const api = process.env.NEXT_PUBLIC_API_URL ?? "";
type Channel = "app" | "email" | "whatsapp";
type Segment = { type: "all" } | { type: "inactive"; days_since_last_visit: number } | { type: "tag"; tag: string } | { type: "high_loyalty"; min_points: number };
interface CampaignTemplate { channel: Channel; content: string; id: string; name: string; variables: string[]; whatsappApprovalStatus?: "approved" | null; whatsappTemplateLocale?: string | null; whatsappTemplateName?: string | null }
interface PreviewRow { customer_id: string; destination: string | null; name: string; reason?: string }
interface Preview { eligible: PreviewRow[]; eligible_count: number; excluded: PreviewRow[]; excluded_count: number }
const channels = [
  { id: "email" as const, icon: Mail, label: "Email", note: "Composizione RTF e anteprima HTML" },
  { id: "whatsapp" as const, icon: MessageCircleMore, label: "WhatsApp", note: "Solo modelli approvati da Meta" },
  { id: "app" as const, icon: Bell, label: "Push app", note: "Titolo e testo breve" },
];

export default function NewCampaignPage() {
  const { salon } = useAuth(); const router = useRouter(); const formRef = useRef<HTMLFormElement>(null);
  const moduleEnabled = useModuleEnabled(MODULE_KEYS.MARKETING);
  const loyaltyEnabled = useModuleEnabled(MODULE_KEYS.LOYALTY);
  const [channel, setChannel] = useState<Channel>("email"); const [segment, setSegment] = useState("all"); const [name, setName] = useState("");
  const [content, setContent] = useState(""); const [selectedTemplateId, setSelectedTemplateId] = useState(""); const [templateParameters, setTemplateParameters] = useState<string[]>([]);
  const [error, setError] = useState(""); const [feedback, setFeedback] = useState(""); const [preview, setPreview] = useState<Preview>();
  const [templates, setTemplates] = useState<CampaignTemplate[]>([]); const [readiness, setReadiness] = useState<Record<Channel, "ready" | "not_configured">>(); const [testDestination, setTestDestination] = useState("");

  useEffect(() => { if (!moduleEnabled) return; if (!salon) return; void Promise.all([fetch(`${api}/api/salons/${salon.id}/campaign-templates`, { credentials: "include" }), fetch(`${api}/api/salons/${salon.id}/campaigns/readiness`, { credentials: "include" })]).then(async ([a, b]) => { if (a.ok) setTemplates(await a.json() as CampaignTemplate[]); if (b.ok) setReadiness(await b.json() as Record<Channel, "ready" | "not_configured">); }); }, [moduleEnabled, salon]);
  function segmentConfig(data: FormData): Segment { if (segment === "inactive") return { type: segment, days_since_last_visit: Number(data.get("days")) }; if (segment === "tag") return { type: segment, tag: String(data.get("tag") ?? "") }; if (segment === "high_loyalty") return { type: segment, min_points: Number(data.get("points")) }; return { type: "all" }; }
  function invalidatePreview() { setPreview(undefined); setFeedback(""); }
  function selectChannel(value: Channel) { setChannel(value); setSelectedTemplateId(""); setTemplateParameters([]); setContent(""); setTestDestination(""); invalidatePreview(); }
  function applyTemplate(id: string) { const template = templates.find((item) => item.id === id); setSelectedTemplateId(id); if (template) { setContent(template.content); setTemplateParameters(template.variables.map(() => "")); } }
  async function loadPreview() { if (!salon || !formRef.current) return; setError(""); const response = await fetch(`${api}/api/salons/${salon.id}/campaigns/preview`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel, target_segment: segmentConfig(new FormData(formRef.current)) }) }); if (!response.ok) return setError("Controlla i filtri del pubblico e riprova."); const result = await response.json() as Preview; setPreview(result); setFeedback(result.eligible_count ? "Pubblico aggiornato." : "Nessun destinatario valido per questo pubblico."); }
  async function sendTest() { if (!salon) return; setError(""); setFeedback(""); if (readiness?.[channel] !== "ready") return setError("Il canale selezionato non è ancora configurato."); const response = await fetch(`${api}/api/salons/${salon.id}/campaigns/test-send`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ channel, content, destination: testDestination, subject: name, ...(channel === "whatsapp" && { template_id: selectedTemplateId, whatsapp_template_parameters: templateParameters }) }) }); if (!response.ok) return setError("Invio di prova non riuscito. Verifica destinatario, consenso e configurazione."); setFeedback("Prova inviata. La campagna è ancora una bozza."); }
  async function create(data: FormData) { if (!salon) return; setError(""); if (!preview?.eligible_count) return setError("Calcola il pubblico prima di salvare la bozza."); if (channel === "whatsapp" && !selectedTemplateId) return setError("Seleziona un modello WhatsApp approvato da Meta."); const response = await fetch(`${api}/api/salons/${salon.id}/campaigns`, { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, channel, target_segment: segmentConfig(data), ...((channel === "email" || channel === "app") && { content }), ...(channel === "whatsapp" && { template_id: selectedTemplateId, whatsapp_template_parameters: templateParameters }), scheduled_at: data.get("scheduled") || undefined }) }); if (!response.ok) return setError("Campagna non salvata. Verifica i dati richiesti per il canale."); const campaign = await response.json() as { id: string }; router.push(`/marketing/${campaign.id}`); }
  const channelTemplates = templates.filter((item) => item.channel === channel && (channel !== "whatsapp" || item.whatsappApprovalStatus === "approved")); const chosen = templates.find((item) => item.id === selectedTemplateId);

  if (!moduleEnabled) {
    return <AppPage maxWidth="max-w-[1600px]">
      <Breadcrumbs items={[{ href: "/marketing", label: "Marketing" }, { label: "Nuova campagna" }]} />
      <div className="mt-5">
        <EmptyState
          action={<Link className="inline-flex min-h-10 items-center rounded-xl bg-[#792f59] px-4 text-sm font-bold text-white shadow-sm hover:bg-[#63204a]" href="/apps">Vai a App e moduli</Link>}
          description="Attiva il modulo Marketing dalla pagina App e moduli per creare una campagna."
          title="Modulo Marketing non attivo"
        />
      </div>
    </AppPage>;
  }

  return <AppPage maxWidth="max-w-[1600px]"><form action={create} ref={formRef}>
    <Breadcrumbs items={[{ href: "/marketing", label: "Marketing" }, { label: "Nuova campagna" }]} />
    <header className="mt-5 flex flex-col gap-4 border-b border-stone-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold tracking-tight text-stone-950">Crea una campagna</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">Scegli prima il canale: ogni percorso mostra solo i dati e i controlli necessari.</p></div><Link className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-[#792f59]" href="/marketing/templates"><LayoutTemplate className="size-4" />Libreria modelli</Link></header>
    {error && <div className="mt-4"><InlineError>{error}</InlineError></div>}{feedback && <p className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800" role="status">{feedback}</p>}
    <div className="mt-5 grid gap-5 xl:grid-cols-12">
      <SectionCard className="xl:col-span-12" title="1. Canale" subtitle="Email, WhatsApp e push hanno regole e contenuti diversi."><div className="grid gap-3 md:grid-cols-3">{channels.map(({ id, icon: Icon, label, note }) => <button aria-pressed={channel === id} className={`min-h-24 rounded-2xl border p-4 text-left transition ${channel === id ? "border-[#792f59] bg-[#fbf3f7] ring-2 ring-[#792f59]/10" : "border-stone-200 bg-white hover:border-stone-300"}`} key={id} onClick={() => selectChannel(id)} type="button"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${channel === id ? "bg-[#792f59] text-white" : "bg-stone-100 text-stone-600"}`}><Icon className="size-5" /></span>{channel === id && <Check className="size-5 text-[#792f59]" />}</div><strong className="mt-3 block text-sm">{label}</strong><span className="mt-1 block text-xs text-stone-500">{note}</span><span className={`mt-2 block text-xs font-semibold ${readiness?.[id] === "ready" ? "text-emerald-700" : "text-amber-700"}`}>{readiness?.[id] === "ready" ? "Pronto" : "Da configurare"}</span></button>)}</div></SectionCard>
      <SectionCard className="xl:col-span-7" title="2. Contenuto" subtitle={channel === "email" ? "Formatta il testo e controlla il risultato HTML." : channel === "whatsapp" ? "Il testo proviene dal modello approvato da Meta e non può essere alterato." : "Mantieni la notifica breve e immediata."}>
        <label className="block text-sm font-semibold">Titolo della campagna<input className="mt-2 min-h-12 w-full rounded-xl border border-stone-200 px-3" onChange={(e) => setName(e.target.value)} placeholder={channel === "app" ? "Titolo della notifica" : "Es. Ritorna da noi"} required value={name} /></label>
        {channelTemplates.length > 0 && <label className="mt-4 block text-sm font-semibold">Modello <Select className="mt-2 min-h-12 w-full" onChange={(e) => applyTemplate(e.target.value)} value={selectedTemplateId}><option value="">Scegli un modello</option>{channelTemplates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></label>}
        {channel === "email" && <div className="mt-4"><RichTextEditor onChange={setContent} value={content} /></div>}
        {channel === "app" && <label className="mt-4 block text-sm font-semibold">Testo della notifica<div className="mt-2"><PushTextEditor onChange={setContent} value={content} /></div></label>}
        {channel === "whatsapp" && <div className="mt-4 space-y-4"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><strong>Iter Meta obbligatorio</strong><p className="mt-1">Puoi usare soltanto un modello già approvato. Nome, lingua e corpo restano bloccati.</p></div>{chosen ? <><dl className="grid gap-3 rounded-xl border border-stone-200 p-4 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">Nome Meta</dt><dd className="font-semibold">{chosen.whatsappTemplateName}</dd></div><div><dt className="text-stone-500">Lingua</dt><dd className="font-semibold">{chosen.whatsappTemplateLocale}</dd></div></dl><div className="rounded-xl bg-stone-50 p-4 text-sm whitespace-pre-wrap">{chosen.content}</div><div className="grid gap-3 sm:grid-cols-2">{chosen.variables.map((variable, index) => <label className="text-sm font-semibold" key={`${variable}-${index}`}>{variable}<input className="mt-2 min-h-12 w-full rounded-xl border border-stone-200 bg-white px-3" onChange={(e) => setTemplateParameters((values) => values.map((value, i) => i === index ? e.target.value : value))} required value={templateParameters[index] ?? ""} /></label>)}</div></> : <p className="rounded-xl border border-dashed border-stone-300 p-6 text-center text-sm text-stone-600">Nessun modello selezionato. Se non ne trovi uno approvato, gestiscilo nella libreria modelli.</p>}</div>}
      </SectionCard>
      <SectionCard className="xl:col-span-5" title={channel === "email" ? "Anteprima HTML" : channel === "app" ? "Anteprima push" : "Contratto Meta"} subtitle="Quello che vedrà il destinatario.">{channel === "email" ? <EmailPreview html={content} salonName={salon?.name} subject={name} /> : channel === "app" ? <PushPreview body={content} title={name} /> : <div className="space-y-3 text-sm"><p className="rounded-xl bg-stone-50 p-4"><strong>1. Crea in Meta</strong><br />Definisci categoria, lingua, corpo e variabili.</p><p className="rounded-xl bg-stone-50 p-4"><strong>2. Attendi l’approvazione</strong><br />Un modello in revisione o rifiutato non è inviabile.</p><p className="rounded-xl bg-stone-50 p-4"><strong>3. Compila i parametri</strong><br />EsseBeauty sostituisce le variabili senza modificare il testo approvato.</p></div>}</SectionCard>
      <SectionCard className="xl:col-span-5" title={<span className="flex items-center gap-2"><UsersRound className="size-5 text-[#792f59]" />3. Pubblico e invio</span>} subtitle="Definisci destinatari e data."><label className="block text-sm font-semibold">Pubblico<Select className="mt-2 min-h-12 w-full" onChange={(e) => { setSegment(e.target.value); invalidatePreview(); }} value={segment}><option value="all">Tutti i clienti</option><option value="inactive">Clienti inattivi</option><option value="tag">Clienti con tag</option>{loyaltyEnabled && <option value="high_loyalty">Clienti fedeli</option>}</Select></label>{segment === "inactive" && <input className="mt-3 min-h-12 w-full rounded-xl border px-3" min="1" name="days" onChange={invalidatePreview} placeholder="Giorni dall’ultima visita" required type="number" />}{segment === "tag" && <input className="mt-3 min-h-12 w-full rounded-xl border px-3" name="tag" onChange={invalidatePreview} placeholder="Tag cliente" required />}{segment === "high_loyalty" && <input className="mt-3 min-h-12 w-full rounded-xl border px-3" min="0" name="points" onChange={invalidatePreview} placeholder="Punti minimi" required type="number" />}<label className="mt-4 block text-sm font-semibold"><span className="flex items-center gap-2"><CalendarClock className="size-4" />Programmazione facoltativa</span><input className="mt-2 min-h-12 w-full rounded-xl border px-3" name="scheduled" type="datetime-local" /></label><Button className="mt-4 w-full" onClick={() => void loadPreview()} type="button" variant="secondary"><Eye className="mr-2 size-4" />Calcola anteprima</Button></SectionCard>
      <SectionCard className="xl:col-span-4" title="Anteprima destinatari" subtitle="Controlla inclusi ed esclusi prima di salvare.">{!preview ? <div className="grid min-h-44 place-items-center rounded-xl border border-dashed border-stone-300 text-center text-sm text-stone-500">Il riepilogo apparirà dopo il calcolo.</div> : <div className="grid gap-3"><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><strong>Destinatari validi · {preview.eligible_count}</strong><p className="mt-1 text-xs text-emerald-800">Primi {preview.eligible.length} mostrati</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><strong>Destinazioni escluse · {preview.excluded_count}</strong><ul className="mt-2 space-y-1 text-xs">{preview.excluded.slice(0, 4).map((item) => <li key={item.customer_id}>{item.name} · {item.reason === "MISSING_EMAIL" ? "email mancante" : item.reason === "MISSING_WHATSAPP_CONSENT" ? "consenso WhatsApp mancante" : item.reason === "MISSING_PUSH_SUBSCRIPTION" ? "push non attive" : "telefono mancante"}</li>)}</ul></div></div>}</SectionCard>
      <SectionCard className="xl:col-span-3" title={<span className="flex items-center gap-2"><Send className="size-5 text-[#792f59]" />Invio di prova</span>} subtitle="Non coinvolge il pubblico della campagna."><input aria-label="Destinazione test" className="min-h-12 w-full rounded-xl border px-3" onChange={(e) => setTestDestination(e.target.value)} placeholder={channel === "email" ? "nome@esempio.it" : "+39…"} value={testDestination} /><Button className="mt-3 w-full" disabled={!content || !testDestination || (channel === "whatsapp" && !selectedTemplateId)} onClick={() => void sendTest()} type="button" variant="secondary"><Send className="mr-2 size-4" />Invia test</Button></SectionCard>
      <div className="esse-panel flex flex-col gap-4 rounded-2xl border border-stone-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between xl:col-span-12"><div><strong className="text-sm">Salva senza inviare</strong><p className="mt-1 text-xs text-stone-500">Potrai rileggere, modificare o eliminare la bozza.</p></div><Button className="min-h-11 sm:min-w-56" disabled={!preview?.eligible_count || !content || !name} type="submit"><Save className="mr-2 size-4" />Salva bozza</Button></div>
    </div>
  </form></AppPage>;
}
