"use client";

import { Check, MoreHorizontal, PackagePlus, SlidersHorizontal } from "lucide-react";
import { Button, EmptyState } from "@esse-beauty/ui";
import type { WarehouseItemType, WarehouseProduct } from "../warehouse-types";

const types: Record<WarehouseItemType, string> = { resale: "Rivendita", consumable: "Consumo", equipment: "Attrezzatura", expense: "Spesa" };
const euro = (cents: number) => (cents / 100).toLocaleString("it-IT", { style: "currency", currency: "EUR" });

export function WarehouseProducts({ items, query, lowOnly, itemType, selected, onQuery, onLowOnly, onItemType, onSelect, onSelectAll, onOpenOperation }: { items: WarehouseProduct[]; query: string; lowOnly: boolean; itemType: WarehouseItemType | "all"; selected: string[]; onQuery(value: string): void; onLowOnly(value: boolean): void; onItemType(value: WarehouseItemType | "all"): void; onSelect(id: string): void; onSelectAll(): void; onOpenOperation(mode: "adjustment" | "waste" | "revaluation", product?: WarehouseProduct): void }) {
  const allSelected = items.length > 0 && items.every((item) => selected.includes(item.id));
  return <div className="grid gap-3">
    <div className="flex flex-wrap items-center gap-2 border border-stone-200 bg-white p-2 shadow-sm"><label className="flex min-h-9 min-w-56 flex-1 items-center rounded-lg border border-stone-200 px-3 text-sm"><span className="sr-only">Cerca articoli</span><input className="w-full outline-none" onChange={(event) => onQuery(event.target.value)} placeholder="Cerca articolo o SKU" value={query} /></label><select aria-label="Tipo articolo" className="min-h-9 rounded-lg border border-stone-200 bg-white px-3 text-sm" onChange={(event) => onItemType(event.target.value as WarehouseItemType | "all")} value={itemType}><option value="all">Tutti i tipi</option>{Object.entries(types).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select><label className="flex min-h-9 items-center gap-2 rounded-lg border border-stone-200 px-3 text-sm"><input checked={lowOnly} onChange={(event) => onLowOnly(event.target.checked)} type="checkbox" />Solo scorte basse</label><Button onClick={() => onOpenOperation("adjustment")} size="sm" variant="secondary"><SlidersHorizontal className="size-3.5" />Azione manuale</Button></div>
    {selected.length > 0 && <div className="flex items-center justify-between border border-[#ead1df] bg-[#fffafd] px-3 py-2 text-sm"><span><strong>{selected.length}</strong> selezionati</span><div className="flex gap-2"><Button onClick={() => onOpenOperation("waste")} size="sm" variant="tableAction"><PackagePlus className="size-3.5" />Registra scarto</Button><Button onClick={() => onOpenOperation("revaluation")} size="sm" variant="tableAction">Rivaluta costo medio</Button></div></div>}
    {items.length === 0 ? <EmptyState description="Modifica i filtri o aggiungi un nuovo articolo." title="Nessun articolo trovato" /> : <div className="overflow-x-auto border border-stone-200 bg-white shadow-sm"><table className="w-full min-w-[980px] text-sm"><thead className="bg-[#faf3f7] text-left text-[10px] font-black uppercase tracking-[.11em] text-[#792f59]"><tr><th className="w-10 px-3 py-2"><input aria-label="Seleziona tutti" checked={allSelected} onChange={onSelectAll} type="checkbox" /></th><th className="px-3 py-2">Articolo</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Scorta</th><th className="px-3 py-2">Costo medio</th><th className="px-3 py-2">Fornitore</th><th className="w-12 px-3 py-2" /></tr></thead><tbody>{items.map((item) => { const low = item.stockQuantity < item.lowStockThreshold; return <tr className="border-t border-stone-100" key={item.id}><td className="px-3 py-2"><input aria-label={`Seleziona ${item.name}`} checked={selected.includes(item.id)} onChange={() => onSelect(item.id)} type="checkbox" /></td><td className="px-3 py-2"><div className="font-bold text-stone-950">{item.name}</div><div className="text-xs text-stone-500">{item.sku || "SKU non impostato"}</div></td><td className="px-3 py-2"><span className="rounded-full bg-stone-100 px-2 py-1 text-[11px] font-bold">{types[item.itemType]}</span></td><td className={`px-3 py-2 font-black ${low ? "text-red-700" : "text-stone-900"}`}>{item.stockQuantity} {item.unit}<div className="text-[11px] font-normal text-stone-500">soglia {item.lowStockThreshold}</div></td><td className="px-3 py-2 font-semibold">{euro(item.averageCostCents)}</td><td className="px-3 py-2 text-stone-600">{item.preferredSupplier || item.supplier || "—"}</td><td className="px-3 py-2"><div className="flex gap-1"><Button aria-label={`Rivaluta ${item.name}`} onClick={() => onOpenOperation("revaluation", item)} size="sm" variant="icon"><Check className="size-4" /></Button><Button aria-label={`Menu ${item.name}`} onClick={() => onOpenOperation("adjustment", item)} size="sm" variant="icon"><MoreHorizontal className="size-4" /></Button></div></td></tr>; })}</tbody></table></div>}
  </div>;
}

