"use client";

import { ExternalLink, RotateCcw } from "lucide-react";
import { Button, EmptyState, StatusBadge } from "@esse-beauty/ui";
import type { WarehouseDocument, WarehouseDocumentKind, WarehouseDocumentStatus, WarehouseSupplier } from "../warehouse-types";

const euro = (cents: number) => (cents / 100).toLocaleString("it-IT", { style: "currency", currency: "EUR" });
const kinds: Record<WarehouseDocumentKind, string> = { adjustment: "Rettifica", count: "Inventario", credit_note: "Nota credito", equipment_purchase: "Acquisto attrezzatura", expense: "Spesa", internal_use: "Uso interno", opening: "Apertura", purchase: "Acquisto", supplier_invoice: "Fattura fornitore", supplier_return: "Reso fornitore", waste: "Scarto" };

export function WarehouseDocuments({ documents, suppliers, status, kind, onStatus, onKind, onOpen, onReverse }: { documents: WarehouseDocument[]; suppliers: WarehouseSupplier[]; status: WarehouseDocumentStatus | "all"; kind: WarehouseDocumentKind | "all"; onStatus(value: WarehouseDocumentStatus | "all"): void; onKind(value: WarehouseDocumentKind | "all"): void; onOpen(documentId: string): void; onReverse(documentId: string): void }) {
  const supplierName = new Map(suppliers.map((supplier) => [supplier.id, supplier.name]));
  return <div className="grid gap-3"><div className="flex flex-wrap items-center gap-2 border border-stone-200 bg-white p-2 shadow-sm"><select aria-label="Stato documento" className="min-h-9 rounded-lg border border-stone-200 bg-white px-3 text-sm" onChange={(event) => onStatus(event.target.value as WarehouseDocumentStatus | "all")} value={status}><option value="all">Tutti gli stati</option><option value="draft">Bozze</option><option value="posted">Registrati</option><option value="reversed">Stornati</option><option value="cancelled">Annullati</option></select><select aria-label="Tipo documento" className="min-h-9 rounded-lg border border-stone-200 bg-white px-3 text-sm" onChange={(event) => onKind(event.target.value as WarehouseDocumentKind | "all")} value={kind}><option value="all">Tutti i tipi</option>{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="ml-auto text-xs text-stone-500">{documents.length} documenti</span></div>{documents.length === 0 ? <EmptyState description="Non ci sono documenti per i filtri scelti." title="Nessun documento" /> : <div className="overflow-x-auto border border-stone-200 bg-white shadow-sm"><table className="w-full min-w-[860px] text-sm"><thead className="bg-[#faf3f7] text-left text-[10px] font-black uppercase tracking-[.11em] text-[#792f59]"><tr><th className="px-3 py-2">Riferimento</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Data</th><th className="px-3 py-2">Fornitore</th><th className="px-3 py-2 text-right">Totale</th><th className="px-3 py-2">Stato</th><th className="px-3 py-2" /></tr></thead><tbody>{documents.map((doc) => <tr className="border-t border-stone-100" key={doc.id}><td className="px-3 py-2 font-bold">{doc.internalNumber}<div className="text-xs font-normal text-stone-500">{doc.externalReference || "nessun riferimento esterno"}</div></td><td className="px-3 py-2">{kinds[doc.kind]}</td><td className="px-3 py-2 text-stone-600">{new Date(doc.documentDate).toLocaleDateString("it-IT")}</td><td className="px-3 py-2 text-stone-600">{doc.supplierId ? supplierName.get(doc.supplierId) || "—" : "—"}</td><td className="px-3 py-2 text-right font-bold">{euro(doc.totalCents)}</td><td className="px-3 py-2"><StatusBadge status={doc.status === "posted" ? "active" : doc.status === "draft" ? "waiting" : "inactive"}>{doc.status}</StatusBadge></td><td className="px-3 py-2"><div className="flex justify-end gap-1"><Button aria-label={`Apri ${doc.internalNumber}`} onClick={() => onOpen(doc.id)} size="sm" variant="icon"><ExternalLink className="size-4" /></Button>{doc.status === "posted" && <Button aria-label={`Storna ${doc.internalNumber}`} onClick={() => onReverse(doc.id)} size="sm" variant="icon"><RotateCcw className="size-4" /></Button>}</div></td></tr>)}</tbody></table></div>}</div>;
}

