"use client";

import { Pencil, Plus } from "lucide-react";
import { Button, EmptyState } from "@esse-beauty/ui";
import type { WarehouseSupplier } from "../warehouse-types";

export function WarehouseSuppliers({ suppliers, onCreate, onEdit }: { suppliers: WarehouseSupplier[]; onCreate(): void; onEdit(supplier: WarehouseSupplier): void }) {
  return <div className="grid gap-3"><div className="flex items-center justify-between border border-stone-200 bg-white p-3 shadow-sm"><div><h2 className="font-bold text-[#402334]">Registro fornitori</h2><p className="text-xs text-stone-500">Anagrafiche disponibili per documenti e riordini.</p></div><Button onClick={onCreate} size="sm" variant="primary"><Plus className="size-3.5" />Nuovo fornitore</Button></div>{suppliers.length === 0 ? <EmptyState description="Crea il primo fornitore per collegarlo agli articoli." title="Nessun fornitore" /> : <div className="overflow-x-auto border border-stone-200 bg-white shadow-sm"><table className="w-full min-w-[760px] text-sm"><thead className="bg-[#faf3f7] text-left text-[10px] font-black uppercase tracking-[.11em] text-[#792f59]"><tr><th className="px-3 py-2">Fornitore</th><th className="px-3 py-2">Contatto</th><th className="px-3 py-2">P.IVA / C.F.</th><th className="px-3 py-2">Pagamento</th><th className="px-3 py-2">Stato</th><th className="px-3 py-2" /></tr></thead><tbody>{suppliers.map((supplier) => <tr className="border-t border-stone-100" key={supplier.id}><td className="px-3 py-2 font-bold">{supplier.name}<div className="text-xs font-normal text-stone-500">{supplier.email || supplier.phone || "nessun contatto"}</div></td><td className="px-3 py-2 text-stone-600">{supplier.contactName || "—"}</td><td className="px-3 py-2 text-stone-600">{supplier.vatNumber || supplier.taxCode || "—"}</td><td className="px-3 py-2 text-stone-600">{supplier.paymentTerms || "—"}</td><td className="px-3 py-2"><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${supplier.active ? "bg-emerald-50 text-emerald-700" : "bg-stone-100 text-stone-500"}`}>{supplier.active ? "Attivo" : "Archiviato"}</span></td><td className="px-3 py-2 text-right"><Button aria-label={`Modifica ${supplier.name}`} onClick={() => onEdit(supplier)} size="sm" variant="icon"><Pencil className="size-4" /></Button></td></tr>)}</tbody></table></div>}</div>;
}

