"use client";

import { ExternalLink, RotateCcw } from "lucide-react";
import { Button, DateField, EmptyState, StatusBadge } from "@esse-beauty/ui";
import type { WarehouseDocument, WarehouseDocumentKind, WarehouseDocumentStatus, WarehouseSupplier } from "../warehouse-types";
import { warehouseDocumentLabel } from "../document-label";

const euro = (cents: number) => (cents / 100).toLocaleString("it-IT", { style: "currency", currency: "EUR" });
const kinds: Record<WarehouseDocumentKind, string> = { adjustment: "Rettifica", count: "Inventario", credit_note: "Nota credito", equipment_purchase: "Acquisto attrezzatura", expense: "Spesa", internal_use: "Uso interno", opening: "Apertura", purchase: "Acquisto", supplier_invoice: "Fattura fornitore", supplier_return: "Reso fornitore", waste: "Scarto" };

export function WarehouseDocuments({ documents, suppliers, status, kind, dateFrom, dateTo, loading, error, onStatus, onKind, onDateFrom, onDateTo, onOpen, onReverse }: { documents: WarehouseDocument[]; suppliers: WarehouseSupplier[]; status: WarehouseDocumentStatus | "all"; kind: WarehouseDocumentKind | "all"; dateFrom: string; dateTo: string; loading: boolean; error: string; onStatus(value: WarehouseDocumentStatus | "all"): void; onKind(value: WarehouseDocumentKind | "all"): void; onDateFrom(value: string): void; onDateTo(value: string): void; onOpen(documentId: string): void; onReverse(documentId: string): void }) {
  const supplierName = new Map(suppliers.map((supplier) => [supplier.id, supplier.name]));
  return <div className="grid gap-3">
    <div className="flex flex-wrap items-end gap-2 border border-stone-200 bg-white p-2 shadow-sm"><select aria-label="Stato documento" className="min-h-11 rounded-lg border border-stone-200 bg-white px-3 text-sm" onChange={(event) => onStatus(event.target.value as WarehouseDocumentStatus | "all")} value={status}><option value="all">Tutti gli stati</option><option value="draft">Bozze</option><option value="posted">Registrati</option><option value="reversed">Stornati</option><option value="cancelled">Annullati</option></select><select aria-label="Tipo documento" className="min-h-11 rounded-lg border border-stone-200 bg-white px-3 text-sm" onChange={(event) => onKind(event.target.value as WarehouseDocumentKind | "all")} value={kind}><option value="all">Tutti i tipi</option>{Object.entries(kinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><div className="min-w-40"><span className="mb-1 block text-xs font-semibold text-stone-500">Da</span><DateField aria-label="Data documento da" onChange={onDateFrom} value={dateFrom} /></div><div className="min-w-40"><span className="mb-1 block text-xs font-semibold text-stone-500">A</span><DateField aria-label="Data documento a" onChange={onDateTo} value={dateTo} /></div><span className="mb-3 ml-auto text-xs text-stone-500">{loading ? "Caricamento…" : `${documents.length} documenti`}</span></div>
    {error && <div aria-live="polite" className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800" role="alert">{error}</div>}
    {loading ? <div className="border border-stone-200 bg-white px-4 py-8 text-center text-sm text-stone-500">Caricamento documenti…</div> : documents.length === 0 ? <EmptyState description="Non ci sono documenti per i filtri scelti." title="Nessun documento" /> : <div className="overflow-x-auto border border-stone-200 bg-white shadow-sm"><table className="w-full min-w-[860px] text-sm"><thead className="bg-[#faf3f7] text-left text-[10px] font-black uppercase tracking-[.11em] text-[#792f59]"><tr><th className="px-3 py-2">Riferimento</th><th className="px-3 py-2">Tipo</th><th className="px-3 py-2">Data</th><th className="px-3 py-2">Fornitore</th><th className="px-3 py-2 text-right">Totale</th><th className="px-3 py-2">Stato</th><th className="px-3 py-2" /></tr></thead><tbody>{documents.map((doc) => <tr className="border-t border-stone-100" key={doc.id}><td className="px-3 py-2 font-bold">{warehouseDocumentLabel(doc)}<div className="text-xs font-normal text-stone-500">{doc.externalReference ? `Rif. interno ${warehouseDocumentLabel({ ...doc, externalReference: null })}` : "nessun riferimento esterno"}</div></td><td className="px-3 py-2">{kinds[doc.kind]}</td><td className="px-3 py-2 text-stone-600">{new Date(doc.documentDate).toLocaleDateString("it-IT")}</td><td className="px-3 py-2 text-stone-600">{doc.supplierId ? supplierName.get(doc.supplierId) || "—" : "—"}</td><td className="px-3 py-2 text-right font-bold">{euro(doc.totalCents)}</td><td className="px-3 py-2"><StatusBadge status={doc.status === "posted" ? "active" : doc.status === "draft" ? "waiting" : "inactive"}>{doc.status}</StatusBadge></td><td className="px-3 py-2"><div className="flex justify-end gap-1"><Button aria-label={`Apri ${warehouseDocumentLabel(doc)}`} onClick={() => onOpen(doc.id)} size="sm" variant="icon" title="Apri documento"><ExternalLink className="size-4" /></Button>{doc.status === "posted" && <Button aria-label={`Storna ${warehouseDocumentLabel(doc)}`} onClick={() => onReverse(doc.id)} size="sm" variant="icon"><RotateCcw className="size-4" /></Button>}</div></td></tr>)}</tbody></table></div>}
  </div>;
}
