import {
  activityLog,
  appointmentRescheduleRequests,
  calendarSettings,
  campaignTemplates,
  consentTemplates,
  customerTags,
  customerConsents,
  customerServicePackages,
  dataExchangeSettings,
  integrationSettings,
  inventoryReorderRequests,
  loginActivity,
  loyaltyAdjustmentReasons,
  loyaltyRewardRedemptions,
  loyaltyTiers,
  notificationPreferences,
  notifications,
  passwordResetTokens,
  platformAuditLog,
  platformImpersonationSessions,
  platformModuleCatalog,
  platformPlans,
  platformSystemTemplates,
  pwaBrandingSettings,
  savedViews,
  salonClosures,
  salonLocations,
  salonResources,
  salonSettings,
  servicePackageUsages,
  servicePackages,
  serviceResources,
  serviceStaff,
  staffAvailabilityRequests,
  userInterfacePreferences,
  inventoryAssets,
  inventoryCountLines,
  inventoryCounts,
  inventoryDocumentLines,
  inventoryDocuments,
  inventoryExpenses,
  inventorySuppliers,
} from "./schema.js";

const plannedTables = [
  activityLog,
  appointmentRescheduleRequests,
  calendarSettings,
  campaignTemplates,
  consentTemplates,
  customerTags,
  customerConsents,
  customerServicePackages,
  dataExchangeSettings,
  integrationSettings,
  inventoryReorderRequests,
  loginActivity,
  loyaltyAdjustmentReasons,
  loyaltyRewardRedemptions,
  loyaltyTiers,
  notificationPreferences,
  notifications,
  passwordResetTokens,
  platformAuditLog,
  platformImpersonationSessions,
  platformModuleCatalog,
  platformPlans,
  platformSystemTemplates,
  pwaBrandingSettings,
  savedViews,
  salonClosures,
  salonLocations,
  salonResources,
  salonSettings,
  servicePackageUsages,
  servicePackages,
  serviceResources,
  serviceStaff,
  staffAvailabilityRequests,
  userInterfacePreferences,
];

if (plannedTables.length !== 37) {
  throw new Error("Schema remediation contract is incomplete.");
}

const warehouseTables = [
  inventorySuppliers,
  inventoryDocuments,
  inventoryDocumentLines,
  inventoryCounts,
  inventoryCountLines,
  inventoryExpenses,
  inventoryAssets,
];

if (warehouseTables.length !== 7 || warehouseTables.some((table) => !table)) {
  throw new Error("Warehouse schema contract is incomplete.");
}
