import {
  activityLog,
  appointmentRescheduleRequests,
  calendarSettings,
  campaignTemplates,
  consentTemplates,
  customerTags,
  customerConsents,
  customerServicePackages,
  dataExchangeSettings,
  integrationSettings,
  inventoryReorderRequests,
  loginActivity,
  loyaltyAdjustmentReasons,
  loyaltyRewardRedemptions,
  loyaltyTiers,
  notificationPreferences,
  notifications,
  passwordResetTokens,
  platformAuditLog,
  platformImpersonationSessions,
  platformModuleCatalog,
  platformPlans,
  platformSystemTemplates,
  pwaBrandingSettings,
  savedViews,
  salonLocations,
  salonResources,
  salonSettings,
  servicePackageUsages,
  servicePackages,
  serviceResources,
  serviceStaff,
  staffAvailabilityRequests,
} from "./schema.js";

const plannedTables = [
  activityLog,
  appointmentRescheduleRequests,
  calendarSettings,
  campaignTemplates,
  consentTemplates,
  customerTags,
  customerConsents,
  customerServicePackages,
  dataExchangeSettings,
  integrationSettings,
  inventoryReorderRequests,
  loginActivity,
  loyaltyAdjustmentReasons,
  loyaltyRewardRedemptions,
  loyaltyTiers,
  notificationPreferences,
  notifications,
  passwordResetTokens,
  platformAuditLog,
  platformImpersonationSessions,
  platformModuleCatalog,
  platformPlans,
  platformSystemTemplates,
  pwaBrandingSettings,
  savedViews,
  salonLocations,
  salonResources,
  salonSettings,
  servicePackageUsages,
  servicePackages,
  serviceResources,
  serviceStaff,
  staffAvailabilityRequests,
];

if (plannedTables.length !== 35) {
  throw new Error("Schema remediation contract is incomplete.");
}
